### ISSUE TITLE
Nested array validation

### ISSUE THREAD

**Issue by edouardsouan** [cangelis/simple-validator#9]
Hi , 

I would like to know if your module support nested array validation and if it does how do you set it up ?

Thank you for your time.

**Comment by cangelis** [comment]
Can you please give an example so I can take a look at what we can do?

**Comment by edouardsouan** [comment]
Yes sorry . 
I would like to be able to validate this kind of array : 
$my_array = [
       'field1' => 'some text',
       'field2' => [ 
               'field21' => 'some text',
               'field22' => [ ...] 
        ]]

Something like that. 

Thanks for your help.

**Comment by cangelis** [comment]
See #15
